### ISSUE TITLE
跳转到下一页后程序退出

### ISSUE THREAD

**Issue by fatFire** [sandboxdream/bilibili_lottery_dynamic_del#3]
![image](https://user-images.githubusercontent.com/33923314/147387664-4bf07c57-6bb4-42a9-a4d2-1e235251752f.png)

如图所示，加载下一页后程序自动退出

**Comment by sandboxdream** [comment]
问题已查出，在修复上个issue时少修改了，此bug的原因是没有指定获取的用户的uid所以无法正常获取而导致程序认为获取结束。我将在元旦时修复此bug

**Comment by sandboxdream** [comment]
完成修复
