### ISSUE TITLE
NameError: name 'podata' is not defined.

### ISSUE THREAD

**Issue by le45tx1m** [sandboxdream/bilibili_lottery_dynamic_del#5]
![QQ截图20221002195657](https://user-images.githubusercontent.com/54882626/193452902-d933e183-d6c4-497e-8606-ab28ed6c9fea.png)

这是啥情况？每次执行到这条都会退出

**Comment by sandboxdream** [comment]
更新到最新版试试？刚刚更新了

**Comment by sandboxdream** [comment]
之前好像是忘了修改函数了

**Comment by le45tx1m** [comment]
嗯，更新后貌似不报错了。
